<div id="bo" class="container d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <div class="card shadow p-4" style="max-width: 400px; width: 100%;">
        <h3 class="text-center mb-4">Cadastro</h3>

        <?php if (!empty($_SESSION['erro_login'])): ?>
            <div class="alert alert-danger">
                <?= $_SESSION['erro_login']; unset($_SESSION['erro_login']); ?>
            </div>
        <?php endif; ?>

        <form method="POST" action="/cadastro/cadastrar" onsubmit=" return validarSenhas()">
            <div class="mb-3">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome" required>
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">E-mail</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>

            <div class="mb-3">
                <label for="senha" class="form-label">Senha</label>
                <input type="password" class="form-control" id="senha" name="senha" required>
            </div>
            <div class="mb-3">
                <label for="confirmar_senha" class="form-label">Confirme sua senha</label>
                <input type="password" class="form-control" id="confirmar_senha" required>
            </div>

            <button type="submit" class="btn btn-success w-100">Cadastrar</button>
        </form>

        <div class="text-center mt-3">
            <a href="/login" class="text-decoration-none">Login</a>
            <span> ou </span>
            <a href="/home" class="text-decoration-none">Voltar ao site</a>
        </div>
    </div>
</div>