<div class="container" style="max-width: 1200px; margin: 40px auto;">

    <h2 class="subtitulo">
        Painel Administrativo — Relatórios
    </h2>

    <div class="card-dashboard">

        <iframe
            src="http://localhost:3000/public/dashboard/b66a81fb-caeb-43b5-ac6b-8c83c8c1d81d"
            frameborder="0"
            width="100%"
            height="490"
        ></iframe>
    </div>

    <div class="card-dashboard">

        <iframe
            src="http://localhost:3000/public/dashboard/2f2ff7d0-8f97-45e4-a932-2f54a60a5f08"
            frameborder="0"
            width="100%"
            height="490"
        ></iframe>
    </div>

</div>