<body class="container">

    <h1 class="subtitulo">Velas Disponíveis</h1>

    <div class="galeria">
        <?php foreach ($velas as $vela): ?>
            <div class="card" style="width: 18rem;">
                <img src="<?= $vela->getImagem() ?>" class="card-img-top" alt="Imagem da vela <?= $vela->getNome() ?>">
                <div class="card-body">
                    <h5 class="subsubtitulo"><?= $vela->getNome() ?></h5>
                    <p class="card-text">
                        Aroma: <?= $vela->getAroma() ?><br>
                        Valor: R$ <?= number_format($vela->getPreco(), 2, ',', '.') ?>
                    </p>


                    <form method="POST" action="/carrinho/add">
                        <input type="hidden" name="id" value="<?= $vela->getId() ?>">

                        <?php if (in_array($vela->getId(), $itensCarrinho)): ?>

                            <button class="btn btn-secondary mt-2" style="padding:5px; margin: 5px; font-size:large;" disabled>
                                ✔ Já está no carrinho
                            </button>

                        <?php else: ?>

                            <button class="btn btn-success mt-2" style="padding:5px; margin: 5px; font-size:large;">
                                🛒 Adicionar ao Carrinho
                            </button>

                        <?php endif; ?>
                    </form>

                    <?php if (!empty($idUsuario)): ?>


                        <form action="/favorito/toggle" method="POST">
                            <input type="hidden" name="id_vela" value="<?= $vela->getId() ?>">
                            <?php if (in_array($vela->getId(), $favoritos)): ?>
                                <button type="submit" class="btn btn-outline-danger btn-sm">
                                    <i class="fa-solid fa-heart"></i> Remover dos favoritos
                                </button>
                            <?php else: ?>
                                <button type="submit" class="btn btn-success btn-sm" title="Adicionar aos favoritos" style="background-color: #ec95d7ff; color: #180c0cff;">
                                    <i class="fa-regular fa-heart"></i> Adicionar aos favoritos
                                </button>
                            <?php endif; ?>
                        </form>
                    <?php else: ?>
                        <div class="alert alert-warning text-center p-2">
                            Faça login para adicionar velas á sua lista de favoritos ❤ ou ao carrinho 🛒.
                        </div>
                        <a href="/login" class="btn btn-success">👤 Login</a>
                    <?php endif; ?>

                </div>
            </div>
        <?php endforeach; ?>
    </div>
</body>