<body class="container">

    <h1 class="subtitulo">Velas Disponíveis</h1>

    <div class="galeria">
        <?php foreach ($velas as $vela): ?>
            <div class="card" style="width: 18rem;">
                <img src="<?= $vela->getImagem() ?>" class="card-img-top" alt="Imagem da vela <?= $vela->getNome() ?>">
                <div class="card-body">
                    <h5 class="subsubtitulo"><?= $vela->getNome() ?></h5>
                    <p class="card-text">
                        Aroma: <?= $vela->getAroma() ?><br>
                        Valor: R$ <?= number_format($vela->getPreco(), 2, ',', '.') ?>
                    </p>

                    <form method="POST" action="/carrinho/add">
                        <input type="hidden" name="id_vela" value="<?= $vela->getId() ?>">
                        <?php if (!empty($_SESSION['id_usuario'])): ?>
                            <button class="btn btn-success mt-2">
                                <i class="fa-regular fa-cart-shopping" style="font-size:60px"></i>Adicionar ao Carrinho
                            </button>
                        <?php else: ?>
                            <a href="/login" class="btn btn-warning mt-2">Faça login para comprar e ou favoritar</a>
                        <?php endif; ?>
                    </form>

                    <?php if (!empty($idUsuario)): ?>


                        <form action="/favorito/toggle" method="POST">
                            <input type="hidden" name="id_vela" value="<?= $vela->getId() ?>">
                            <?php if (in_array($vela->getId(), $favoritos)): ?>
                                <button type="submit" class="btn btn-outline-danger btn-sm">
                                    <i class="fa-solid fa-heart"></i> Remover dos favoritos
                                </button>
                            <?php else: ?>
                                <button type="submit" class="btn btn-success btn-sm" title="Adicionar aos favoritos">
                                    <i class="fa-regular fa-heart"></i> Adicionar aos favoritos
                                </button>
                            <?php endif; ?>
                        </form>
                    <?php else: ?>
                        <div class="alert alert-warning text-center p-2">
                            Faça login para adicionar velas na sua lista de favoritos.
                        </div>
                    <?php endif; ?>

                </div>
            </div>
        <?php endforeach; ?>
    </div>
</body>