<form method="post" action="/product/create">
    <h2>Cadastro</h2>

    <label for="nome">Nome Completo:</label>
    <input type="text" id="nome" name="nome" required>

    <label for="descricao">E-mail:</label>
    <input type="descricao" id="descricao" name="descricao" required>

    <label for="preco">preco:</label>
    <input type="number" id="preco" name="preco">

    <label for="categoria">categoria:</label>
    <input type="text" id="categoria" name="categoria" maxlength="14" required>

    <button type="submit">Cadastrar</button>
</form>

<h1>Lista de Produtos</h1>

<table>
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Preco</th>
        <th>Categoria</th>
    </tr>
    <?php /** @var Product */ ?>
    <?php foreach ($products as $product): ?>
        <tr>
            <td><?= $product->getId() ?></td>
            <td><?= $product->getNome() ?></td>
            <td><?= $product->getDescricao() ?></td>
            <td><?= $product->getPreco() ?></td>
            <td><?= $product->getCategoria() ?></td>
        </tr>
    <?php endforeach ?>
</table>