<?php

namespace DoctrineProxies\__CG__\App\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vela extends \App\Model\Vela implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aroma' => [parent::class, 'aroma', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imagem' => [parent::class, 'imagem', null, 16],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null, 16],
        "\0".parent::class."\0".'preco' => [parent::class, 'preco', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'aroma' => [parent::class, 'aroma', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imagem' => [parent::class, 'imagem', null, 16],
        'nome' => [parent::class, 'nome', null, 16],
        'preco' => [parent::class, 'preco', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
